---
- hosts: homework_vms
  tasks:
    - name: nginx_test
      uri:
        url: http://localhost:8085
        return_content: yes
    - name: web_1_test
      uri:
        url: http://localhost:5001
        return_content: yes
    - name: web_2_test
      uri:
        url: http://localhost:5002
        return_content: yes
    - name: web_3_test
      uri:
        url: http://localhost:5003
        return_content: yes
